<?php  require $_SERVER['DOCUMENT_ROOT'] . '/spring_2022/csis408/social02/env/include.phtml'; ?>

<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<title>Page Title</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="/spring_2022/csis408/social02/library/css/main.css">
<style>
</style>
<script src=""></script>
<body>
<?php
  echo BuildNavigation();
?>
  <div class="container">
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10 debug">
        <div class="border-2 rounded-3 px-3 pt-5">
<?php
$sql = "SELECT u.full_name, u.image AS user_image, u.image_type AS user_image_type, u.is_deleted AS user_is_deleted, p.id, p.text, p.user_id, p.image, p.image_type, p.datetime_add, p.is_deleted FROM posts p LEFT JOIN users u ON u.id = p.user_id LEFT JOIN friendswith fw ON fw.user1_id = p.user_id OR fw.user2_id = p.user_id WHERE (fw.user1_id = 1 OR fw.user2_id = 1) AND p.user_id != 1 ORDER BY p.datetime_add DESC";
if($result = mysqli_query($DB, $sql)){
    if(mysqli_num_rows($result) > 0){
        $row = mysqli_fetch_array($result);
        echo "<div class=post>";
            // TODO Fix profile picture display
            echo "blah4";
            // if(!is_null($result['user_image']) && !is_null($result['user_image_type'])){
            //     // echo '<img src="data:image/' . $result['user_image_type'] . ';base64,'.base64_encode($row['user_image']).'"/>';
            //     echo "there's supposed to bve an image here";
            // }

            // echo $result['user_image_type'];

            echo "<div class=username>" . $row['full_name'] . "</div>";
            echo "<p class=caption>" . $row['text'] . "</p>";
            // TODO Add image
            // Reactions
            $sqllikes = "SELECT COUNT(user_id) AS likes FROM reactions WHERE post_id = " . $row['id'] . " AND is_like = 1";
            if($resultlikes = mysqli_query($DB, $sqllikes)){
                if(mysqli_num_rows($resultlikes) > 0){
                    $rowlikes = mysqli_fetch_array($resultlikes);
                    echo "<div class=reactions>" . $rowlikes['likes'] . " likes, ";
                    // Free result set
                    mysqli_free_result($resultlikes);
                } else {
                    echo "<div class=reactions>0 likes, ";
                }
            }

            $sqldislikes = "SELECT COUNT(user_id) AS dislikes FROM reactions WHERE post_id = " . $row['id'] . " AND is_like = 0";
            if($resultdislikes = mysqli_query($DB, $sqldislikes)){
                if(mysqli_num_rows($resultdislikes) > 0){
                    $rowdislikes = mysqli_fetch_array($resultdislikes);
                    echo $rowdislikes['dislikes'] . " dislikes</div>";
                    // Free result set
                    mysqli_free_result($resultdislikes);
                } else {
                    echo "0 dislikes</div>";
                }
            }

        echo "</div>";

        // Free result set
        mysqli_free_result($result);
    } else {
        echo "No posts yet! Make some friends to get started.";
    }
}
?>
        </div>
      </div>
      <div class="col-1"></div>
    </div>
  </div>
</body>
</html>