<?php  

  require $_SERVER['DOCUMENT_ROOT'] . '/spring_2022/csis408/social02/env/include.phtml';

  // Ensure the user is logged in to a valid 'user' level.
  if($myACCOUNT_TYPE !== 'users')
  {
    HeaderLocation(WEB_ROOT . '/html/login.phtml');
    exit;
  }

?>
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<title>Home | Social 02</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/library/css/main.css">
<link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/library/css/bootstrap.min.css">
<style>
</style>
<script src=""></script>
<body>
<?php
  echo BuildNavigation();
?>
  <div class="container">
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10 debug">
        <div class="border-2 rounded-3 px-3 pt-5">
<?php
$sql = "SELECT u.full_name, u.image_id AS user_image_id, u.is_deleted AS user_is_deleted, p.id, p.text, p.user_id, p.image_id, p.datetime_add, p.is_deleted FROM posts p LEFT JOIN users u ON u.id = p.user_id LEFT JOIN friendswith fw ON fw.user1_id = p.user_id OR fw.user2_id = p.user_id WHERE (fw.user1_id = " . $_SESSION['USER_ID'] . " OR fw.user2_id = " . $_SESSION['USER_ID'] . ") AND p.user_id != " . $_SESSION['USER_ID'] . " ORDER BY p.datetime_add DESC";
if($result = mysqli_query($DB, $sql)){
  if(mysqli_num_rows($result) > 0){
    while($row = mysqli_fetch_array($result)){
      echo "<div class=post id=post" . $row['id'] . ">";
      // TODO Fix profile picture display
      echo "Test 1";
      if(!is_null($row['user_image_id'])){
        echo '<img src="' . WEB_ROOT . '/env/image_get.phtml?image_id=' . $row['user_image_id'] . '"/>';
        echo "there's supposed to be an image here";
      }

      echo $row['user_image_type'];

      echo "<div class=username>" . $row['full_name'] . "</div>";
      echo "<p class=caption>" . $row['text'] . "</p>";
      // TODO Add image
      // Reactions
      $sqllikes = "SELECT COUNT(user_id) AS likes FROM reactions WHERE post_id = " . $row['id'] . " AND is_like = 1";
      if($resultlikes = mysqli_query($DB, $sqllikes)){
        if(mysqli_num_rows($resultlikes) > 0){
          $rowlikes = mysqli_fetch_array($resultlikes);
          echo "<div class=reactions>" . $rowlikes['likes'] . " likes, ";
          // Free result set
          mysqli_free_result($resultlikes);
        } else {
          echo "<div class=reactions>0 likes, ";
        }
      }

      $sqldislikes = "SELECT COUNT(user_id) AS dislikes FROM reactions WHERE post_id = " . $row['id'] . " AND is_like = 0";
      if($resultdislikes = mysqli_query($DB, $sqldislikes)){
        if(mysqli_num_rows($resultdislikes) > 0){
          $rowdislikes = mysqli_fetch_array($resultdislikes);
          echo $rowdislikes['dislikes'] . " dislikes</div>";
          // Free result set
          mysqli_free_result($resultdislikes);
        } else {
          echo "0 dislikes</div>";
        }
      }

      echo "</div>";
    }

    // Free result set
    mysqli_free_result($result);
  } else {
      echo "No posts yet! Make some friends to get started.";
  }
}
?>
        </div>
      </div>
      <div class="col-1"></div>
    </div>
  </div>
</body>
</html>