<?php  

  require $_SERVER['DOCUMENT_ROOT'] . '/spring_2022/csis408/social02/env/include.phtml';

  // Get the variable names
  $xTEXT = PostVar('xTEXT', '');

  // Ensure the user is logged in to a valid 'user' level.
  if($myACCOUNT_TYPE !== 'users')
  {
    HeaderLocation(WEB_ROOT . '/html/login.phtml');
    exit;
  }

  $POST = array();
  if(isset($_POST['xSUBMIT'])) {
    $POST['USER_ID'] = $_SESSION['USER_ID'];
    $POST['TEXT'] = $xTEXT;
    echo "The posted post has posted";
    if(DB_Insert('posts', $POST) != -1) {
      HeaderLocation(WEB_ROOT . '/html/' . $acc_type . '/index.phtml');
    } else echo 'Post creation failed. Please wait some time then try again.';
  }

?>

<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<title>Login | Social 02</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/library/css/main.css">
<link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/library/css/bootstrap.min.css">
<style>
</style>
<body>
<?php
  echo BuildNavigation();
?>

<div class="container">
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10 debug">
        <div class="border-2 rounded-3 px-3 pt-5">
          <form name="xFORM" method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>" enctype="multipart/form-data" class="px-5 pt-5">
            <div class="mb-3 mt-3">
              <label for="xTEXT" class="form-label">Post Text</label>
              <textarea id="xTEXT" name="xTEXT" class="form-control"></textarea>
            </div>
            <div class="col-auto">
              <input type=submit name="xSUBMIT">
            </div>
          </form>
        </div>
      </div>
      <div class="col-1"></div>
    </div>
  </div>
</body>
</html>