<?php

  require $_SERVER['DOCUMENT_ROOT'] . '/spring_2022/csis408/social02/env/include.phtml';

  // Redirect the user to the home page for logging in
  HeaderLocation(WEB_ROOT . '/html/login.phtml');
  exit;

?>
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<title>Home | Social 02</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="">
<style>
</style>
<script src=""></script>
<body>
</body>
</html>