<?

  require $_SERVER['DOCUMENT_ROOT'] . '/spring_2022/csis408/social02/env/include.phtml';

  // Get the variable names
  $xTASK = PostVar('xTASK', '');
  $xUSERNAME = PostVar('xUSERNAME', '');
  $xPASSWORD = PostVar('xPASSWORD', '');
  $xFULLNAME = PostVar('xFULLNAME', '');

  $USER = array();
  if($xTASK === 'INSERT')
  {
    $USER['username'] = $xUSERNAME;
    $USER['password'] = $xPASSWORD;
    $USER['fullname'] = $xFULLNAME;

    var_dump($USER);
  }
  var_dump($xTASK);

?>
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<title>Page Title</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="">
<style>
</style>
<script src="">
  function Validate(theform, thetask)
  {
    if(theform.xUSERNAME.value === '')
    {
      console.log("Username sucks");
    }
  }

</script>
<body>
  <form method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>" enctype="multipart/form-data">
    <label for="xUSERNAME">Username</label>
    <input type="text" id="xUSERNAME" name="xUSERNAME"><br>
    <label for="xFULLNAME">Full Name</label>
    <input type="text" id="xFULLNAME" name="xFULLNAME"><br>
    <label for="xPASSWORD">Password</label>
    <input type="password" id="xPASSWORD" name="xPASSWORD"><br>
    <label for="xPROFILEPICTURE">Upload a Profile Picture</label>
    <input type="file" id="xPROFILEPICTURE" name="xPROFILEPICTURE"><br>
    <input type="submit" value="INSERT" name="xTASK">
  </form>
</body>
</html>