<?

  require $_SERVER['DOCUMENT_ROOT'] . '/spring_2022/csis408/social02/env/include.phtml';

  // Get the variable names
  $xTASK = PostVar('xTASK', '');
  $xUSERNAME = PostVar('xUSERNAME', '');
  $xPASSWORD = PostVar('xPASSWORD', '');
  $xFULLNAME = PostVar('xFULLNAME', '');
  $xISADMIN = PostVar('xISADMIN', '0');
  $xPROFILEPICTURE = PostFile('xPROFILEPICTURE');

  // Redirect the user to the appropriate landing page
  if(isset($_SESSION['USER_ID']))
  {
    echo 'You are currently logged in as "' . $_SESSION['USER_ARRAY']['full_name'] . '"<br>' . "\n";
    echo 'This account is a ' . $_SESSION['USER_TYPE'] . '<br>' . "\n";
    // header('Location: ' . PROJECT_HTML . '/' . $_SESSION['USER_TYPE'] . '/index.phtml');
    // exit;
  }

  // Sanitize the input
  if($xTASK === 'REGISTER')
  {
    if(preg_match("[^A-Za-z0-9]", $xUSERNAME) || strlen($xUSERNAME) > 64) {
      // TODO Error
    }

  }

  $USER = array();
  if($xTASK === 'REGISTER')
  {
    $USER['username'] = $xUSERNAME;
    $USER['password'] = $xPASSWORD;
    $USER['fullname'] = $xFULLNAME;
    $USER['is_admin'] = $xISADMIN;
    $USER['status'] = '';
    $USER['is_deleted'] = 0;

    // Search for the user with the given username and password
    $okay = DB_Insert('users', $USER);
    if(!$okay)
    {
      echo 'Failed to insert the new record. ';
      // echo $DB->error_get_last();
    }

    if($okay)
    {
      $acc_type = ($user[0]['is_admin'] === 0) ? 'users' : 'administrators';
      $_SESSION['USER_ARRAY'] = $user[0];
      $_SESSION['USER_ID'] = $user[0]['id'];
      $_SESSION['USER_TYPE'] = $acc_type;
      header('Location: ' . PROJECT_HTML . '/' . $acc_type . '/index.phtml');
      exit;
    }
  }

?>
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<title>Register Account | Social 02</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="">
<style>
</style>
<script>
  function Validate(theform, thetask)
  {
    var okay = false;
    do
    {
      // Verify the username is not empty
      if(theform.xUSERNAME.value === '')
      {
        console.log("Username sucks");
      }

      okay = true;
    }
    while(0);

    // Submit the form if all checks succeed
    if(okay)
    {
      theform.xTASK.value = thetask;
      theform.submit();
    }
  }

</script>
<body>
  <form name="xFORM" method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>" enctype="multipart/form-data">
    <input type="hidden" name="xTASK" value="">
    <label for="xUSERNAME">Username</label>
    <input type="text" id="xUSERNAME" name="xUSERNAME"><br>
    <label for="xFULLNAME">Full Name</label>
    <input type="text" id="xFULLNAME" name="xFULLNAME"><br>
    <label for="xPASSWORD">Password</label>
    <input type="password" id="xPASSWORD" name="xPASSWORD"><br>
    <label for="xPROFILEPICTURE">Upload a Profile Picture</label>
    <input type="file" id="xPROFILEPICTURE" name="xPROFILEPICTURE"><br>
    <button onclick="Validate(document.xFORM, 'REGISTER')">
  </form>
</body>
</html>