<?

  require $_SERVER['DOCUMENT_ROOT'] . '/spring_2022/csis408/social02/env/include.phtml';

  // Get the variable names
  $xTASK = PostVar('xTASK', '');
  $xUSERNAME = PostVar('xUSERNAME', '');
  $xPASSWORD = PostVar('xPASSWORD', '');
  $xFULLNAME = PostVar('xFULLNAME', '');
  $xISADMIN = PostVar('xISADMIN', '0');
  $xIMAGE = PostFile('xIMAGE');

  // Sanitize the input
  if($xTASK === 'REGISTER')
  {
    $xTASK_HOLD = $xTASK;
    $xTASK = '';

    $okay = false;
    do
    {
      // Ensure the username passes validation
      if(preg_match("[^A-Za-z0-9]", $xUSERNAME) || strlen($xUSERNAME) > 64) {
        $DEBUG_MESSAGE = 'The username has not passed verification. Please ensure the username is alphanumeric and less than 64 characters';
        break;
      }

      // Ensure the password passes validation
      if(preg_match("[^A-Za-z0-9]", $xPASSWORD) || strlen($xPASSWORD) > 64) {
        $DEBUG_MESSAGE = 'The password has not passed verification. Please ensure the username is alphanumeric and less than 64 characters';
        break;
      }

      // Ensure the ISADMIN button is safe.
      $okay = ($xISADMIN === '1') || ($xISADMIN === '0');
      if(!$okay)
      {
        $DEBUG_MESSAGE = 'The Administrator Request button has been fiddled with!';
        break;
      }

      // Make sure the username is fully unique
      $tmp_user = array();
      $tmp_user['username'] = $xUSERNAME;
      $return = DB_Search('users', $tmp_user);

      $okay = (count($return) === 0);
      unset($return, $tmp_user);
      if(!$okay)
      {
        $DEBUG_MESSAGE = 'The username is already in use. Please try another.';
        break;
      }

      $okay = true;
    }
    while(0);

    // Reset the $xTASK to the original value
    if($okay)
    {
      $xTASK = $xTASK_HOLD;
      unset($xTASK_HOLD);
    }
  }

  $USER = array();
  $IMAGE = array();
  if($xTASK === 'REGISTER')
  {
    $okay = false;

    do
    {
      // Insert Image if found
      $new_id = 0;
      if(($xIMAGE['error'] === UPLOAD_ERR_OK) && (file_exists($xIMAGE['tmp_name'])))
      {
        $timestamp = date('Y-m-d H:i:s');
        $img_data = base64_encode(@file_get_contents($xIMAGE['tmp_name']));
        $IMAGE['image_name'] = $xIMAGE['name'];
        $IMAGE['image_size'] = $xIMAGE['size'];
        $IMAGE['image_type'] = $xIMAGE['type'];
        $IMAGE['timestamp'] = $timestamp;
        $IMAGE['image_data'] = $img_data;
        $okay = DB_Insert('images', $IMAGE);

        // Ensure the insert is successful
        if(!$okay)
        {
          echo 'Failed to upload the user image. ';
          break;
        }

        unset($IMAGE['image_data']); // Don't search by this
        $record = DB_Search('images', $IMAGE);
        $record = array_pop($record);
        $new_id = $record['image_id'];
      }
      else
      {
        $DEBUG_MESSAGE = $xIMAGE['error'] . ' - Image Error!';
        break;
      }

      // Update User Information
      $USER['username'] = $xUSERNAME;
      $USER['password'] = $xPASSWORD;
      $USER['full_name'] = $xFULLNAME;
      $USER['is_admin'] = $xISADMIN;
      $USER['image_id'] = $new_id; // Some image ID
      $USER['status'] = '';
      $USER['is_deleted'] = 0;

      // Search for the user with the given username and password
      $okay = DB_Insert('users', $USER);
      if(!$okay)
      {
        echo 'Failed to create the new user. ';
        echo $DB->error_get_last();
        break;
      }
    }
    while(0);

    if($okay)
    {
      $acc_type = ($USER[0]['is_admin'] === '1') ? 'administrators' : 'users';
      $_SESSION['USER_ARRAY'] = $USER[0];
      $_SESSION['USER_ID'] = $USER[0]['id'];
      $_SESSION['USER_TYPE'] = $acc_type;
      HeaderLocation(WEB_ROOT . '/html/' . $acc_type . '/index.phtml?REF=NEW');
      exit;
    }
  }

?>
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<title>Register Account | Social 02</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/library/css/main.css">
<link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/library/css/bootstrap.min.css">
<style>
</style>
<script>
  function Validate(theform, thetask)
  {
    var okay = false;
    do
    {
      // Verify the username is not empty
      if(theform.xUSERNAME.value === '')
      {
        console.log("Please ensure the username is not empty!");
        break;
      }

      // Verify the password is not empty
      if(theform.xPASSWORD.value === '')
      {
        console.log("Please ensure the password is not empty!");
        break;
      }

      // Verify the full name is not empty
      if(theform.xFULLNAME.value === '')
      {
        console.log("Please ensure the user's full name is not empty!");
        break;
      }

      okay = true;
    }
    while(0);

    // Submit the form if all checks succeed
    if(okay)
    {
      theform.xTASK.value = thetask;
      theform.submit();
    }

    return false;
  }

</script>
<body>
<?php echo BuildNavigation(); ?>
<div class="container">
<div class="row">
    <div class="col-12 text-center px-3 pt-5 DEBUG_MESSAGE">
      <p>
<?php
  echo $DEBUG_MESSAGE;
?>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-10 debug">
      <div class="border-2 rounded-3 px-3 pt-5">
        <div>
          <h5 class="text-center">Create your <bold><em>Social 02</em></bold> Account</h5>
        </div>
        <form name="xFORM" method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>" enctype="multipart/form-data" class="px-5 pt-5">
          <input type="hidden" name="xTASK" value="">
          <div class="mb-3 mt-3">
            <label for="xUSERNAME" class="form-label">Username</label>
            <input type="text" id="xUSERNAME" name="xUSERNAME" class="form-control">
          </div>
          <div class="mb-3 mt-3">
            <label for="xPASSWORD" class="form-label">Password</label>
            <input type="password" id="xPASSWORD" name="xPASSWORD" class="form-control">
          </div>
          <div class="mb-3 mt-3">
            <label for="xFULLNAME" class="form-label">Full Name</label>
            <input type="text" id="xFULLNAME" name="xFULLNAME" class="form-control">
          </div>
          <div class="mb-3 mt-3">
            <label for="xIMAGE" class="form-label">Profile Picture</label>
            <input type="file" id="xIMAGE" name="xIMAGE" class="form-control">
          </div>
          <div class="mb-3 mt-3">
            <input type="checkbox" id="xISADMIN" name="xISADMIN" class="form-check-input" value="1">
            <label for="xISADMIN" class="form-check-label">Request Administrator</label>
          </div>
          <div class="col-auto">
            <button onclick="Validate(document.xFORM, 'REGISTER')" class="btn btn-primary mb-3">Login</button>
          </div>
        </form>
      </div>
    </div>
    <div class="col-1"></div>
  </div>
</div>
</body>
</html>