<?php

  require $_SERVER['DOCUMENT_ROOT'] . '/spring_2022/csis408/social02/env/include.phtml';

  $USER = GetVar('USER', '');
  $xUSER = PostVar('xUSER', $USER);

  $all_users = array();
  $all_images = array();
  if($xUSER !== '')
  {
    $str_search = strtolower($xUSER);

    // Initialize the search query
    $query = 'SELECT * FROM users WHERE username LIKE \'%' . $str_search . '%\' OR username = \'' . $str_search . '\' OR full_name LIKE \'%' . $str_search .'%\'';

    $all_users = array();
    $result = $DB->query($query);
    while($row = $result->fetch_array(MYSQLI_ASSOC))
    {
      $all_users[] = $row;
    }

    $all_image_ids = array();
    foreach($all_users as $user)
    {
      if(($user['image_id'] === NULL) || ($user['image_id'] === 0))
      {
        continue;
      }

      // Add all valid ids to the list
      $all_image_ids[] = $user['image_id'];
    }

    $query = '';
    $query = 'SELECT * FROM images WHERE 1 = 0 OR';
    foreach($all_image_ids as $id)
    {
      $query .= ' image_id = \'' . $id . '\' OR';
    }
    $query = rtrim($query, ' OR');

    $all_images = array();
    $result = $DB->query($query);
    while($row = $result->fetch_array(MYSQLI_ASSOC))
    {
      $all_images[$row['image_id']] = $row;
    }
  }

?>
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<title>Searching for <?php echo $USER; ?> | Social Dos</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/library/css/main.css">
<link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/library/css/bootstrap.min.css">
<style>
</style>
<script src=""></script>
<body>
<?php
  echo BuildNavigation();
?>
  <div class="container">
    <div class="mt-3 bg-light border-2 rounded-3">
      <div class="row align-content-center align-middle">
        <div class="col-3 border-bottom"></div>
        <div class="col-6 border-bottom">
          <div class="border-2 rounded-3 px-3 pt-5">
            <form name="xSEARCH" class="d-flex" method="GET" action="<?php echo $_SERVER['PHP_SELF']; ?>" enctype="multipart/form-data">
              <input name="USER" class="form-control me-2" type="search" placeholder="Search @username" aria-label="Search" value="<?php echo $USER; ?>">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
        <div class="col-3 border-bottom"></div>
      </div>
      <div class="row">
        <div class="col-1"></div>
        <div class="col-10 debug">
          <div class="border-2 rounded-3 px-3 pt-5">
<?php

  $spaces = '          ';
  if(count($all_users) > 0)
  {
    // echo $spaces . '<div class="px-3 py-3">' . "\n";
    echo $spaces . '<div class="mb-2"><h4>Listing all users matching \'' . strtolower($USER) . '\'</h4><div>' . "\n";
    echo $spaces . '  <table class="table table-striped table-hover">' . "\n";
    echo $spaces . '    <thead>' . "\n";
    echo $spaces . '      <tr>' . "\n";
    echo $spaces . '        <td>icon</td>' . "\n";
    echo $spaces . '        <td>Username</td>' . "\n";
    echo $spaces . '        <td>Options</td>' . "\n";
    echo $spaces . '    </tr>' . "\n";
    echo $spaces . '    </thead>' . "\n";
    echo $spaces . '    <tbody>' . "\n";
    foreach($all_users as $cnt => $user)
    {
      $image = (isset($all_images[$user['image_id']])) ? $all_images[$user['image_id']] : array('image_id' => '0', 'image_type' => '', 'image_data' => '');

?>
                <tr id=<?php echo $user['username'] ?>>
                  <td>
                    <div class="profile px-2">
                      <img src="<?php echo WEB_ROOT . '/env/feeder.phtml?GET=IMG&ID=' . $image['image_id']; ?>" style="width: 40px;" class="rounded-pill">
                    </div>
                  </td>
                  <td>
                    <div class="username align-baseline">
                      <a href="<?php echo WEB_ROOT . '/html/profile.phtml?USER=' . urlencode($user['username']); ?>"><p><?php echo $user['username']; ?></p></a>
                    </div>
                  </td>
                  <td>
                    <div class="friend">
                      <?php
                        if($user['id'] != $_SESSION['USER_ID']) { // Disallow user becoming friends with himself
                          $sqlfriend = "SELECT * FROM friendswith fw WHERE (fw.user1_id = " . $_SESSION['USER_ID'] . " AND fw.user2_id = " . $user['id'] . ") OR (fw.user1_id = " . $user['id'] . " AND fw.user2_id = " . $_SESSION['USER_ID'] . ")";
                          if($resultfriend = mysqli_query($DB, $sqlfriend)){
                            if(mysqli_num_rows($resultfriend) > 0){
                              // They are friends
                              echo '<a class="btn btn-secondary" href="' . WEB_ROOT . '/env/friend.phtml?FRIEND_ID=' . $user['id'] . '&QUERY=' . $_GET['USER'] . '" role="button">Remove Friend</a>';
                            } else {
                              // They are not friends
                              echo '<a class="btn btn-primary" href="' . WEB_ROOT . '/env/friend.phtml?FRIEND_ID=' . $user['id'] . '&QUERY=' . $_GET['USER'] . '" role="button">Add Friend</a>';
                            }
                          }
                        }

                        if($_SESSION['USER_TYPE'] == "administrators" && $user['id'] != $_SESSION['USER_ID']) {
                          echo '<a class="btn btn-danger" href="' . WEB_ROOT . '/env/deleteuser.phtml?DELETE_ID=' . $user['id'] . '&QUERY=' . $_GET['USER'] . '" role="button" style="margin-left: 10px;">Delete User</a>';
                        }
                      ?>
                      
                      
                    </div>
                  </td>
                </tr>
            <!-- </div> -->
<?php

    }
    echo $spaces . '    </tbody>' . "\n";
    echo $spaces . '  </table>' . "\n";
    echo $spaces . '</div>' . "\n";
  }

?>
          </div>
        </div>
        </div>
        <div class="col-1"></div>
      </div>
    </div>
  </div>
</body>
</html>