<?php

  require $_SERVER['DOCUMENT_ROOT'] . '/spring_2022/csis408/social02/env/include.phtml';

?>
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<title>Home | Social 02</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/library/css/bootstrap.min.css">
<style>
</style>
<script>
  function Validate(theform, thetask)
  {
    var okay = false;
    do
    {
      // Verify the username is not empty
      if(theform.xUSERNAME.value === '')
      {
        console.log("The username cannot be empty.");
        break;
      }

      if(theform.xPASSWORD.value === '')
      {
        console.log("The password cannot be empty.");
        break;
      }

      okay = true;
    }
    while(0);

    // Submit the form if all checks succeed
    if(okay)
    {
      theform.xTASK.value = thetask;
      theform.submit();
    }

    return false;
  }

</script>
<body>
<?php
  echo BuildNavigation();
?>
  <div class="container">
    <div class="row">
      <div class="col"></div>
      <div class="col debug">
        <form name="xFORM" method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>" enctype="multipart/form-data">
          <input type="hidden" name="xTASK" value="">
          <div class="mb-3 mt-3">
            <label for="xUSERNAME" class="form-label">Username</label>
            <input type="text" id="xUSERNAME" name="xUSERNAME" class="form-control">
          </div>
          <div class="mb-3 mt-3">
            <label for="xPASSWORD" class="form-label">Password</label>
            <input type="password" id="xPASSWORD" name="xPASSWORD" class="form-control">
          </div>
          <div class="col-auto">
            <button onclick="Validate(document.xFORM, 'LOGIN')" class="btn btn-primary mb-3">Login</button>
          </div>
        </form>
      </div>
      <div class="col"></div>
    </div>
  </div>
</body>
</html>