<?php

  require $_SERVER['DOCUMENT_ROOT'] . '/spring_2022/csis408/social02/env/include.phtml';

  // Get the variable names
  $xTEXT = PostVar('xTEXT', '');
  $xSUBMIT = PostVar('xSUBMIT');
  $xIMAGE = PostFile('xIMAGE');

  // Ensure the user is logged in to a valid 'administrator' level.
  if($myACCOUNT_TYPE !== 'administrators')
  {
    HeaderLocation(WEB_ROOT . '/html/login.phtml');
    exit;
  }

  $POST = array();
  if(isset($_POST['xSUBMIT'])) {

    $new_id = 0;
    do
    {
      if(($xIMAGE['error'] === UPLOAD_ERR_OK) && (file_exists($xIMAGE['tmp_name'])))
      {
        $timestamp = date('Y-m-d H:i:s');
        $img_data = base64_encode(@file_get_contents($xIMAGE['tmp_name']));
        $IMAGE['image_name'] = $xIMAGE['name'];
        $IMAGE['image_size'] = $xIMAGE['size'];
        $IMAGE['image_type'] = $xIMAGE['type'];
        $IMAGE['timestamp'] = $timestamp;
        $IMAGE['image_data'] = $img_data;
        $okay = DB_Insert('images', $IMAGE);

        // Ensure the insert is successful
        if(!$okay)
        {
          echo 'Failed to upload the user image. ';
          break;
        }

        unset($IMAGE['image_data']); // Don't search by this
        $record = DB_Search('images', $IMAGE);
        $record = array_pop($record);
        $new_id = $record['image_id'];
      }
      else
      {
        // Ignore -- Images are not required
      }

      $POST['USER_ID'] = $_SESSION['USER_ID'];
      $POST['TEXT'] = $xTEXT;
      $POST['image_id'] = $new_id;

      if(DB_Insert('posts', $POST) != -1) {
        HeaderLocation(WEB_ROOT . '/html/' . $acc_type . '/index.phtml');
      } else echo 'Post creation failed. Please wait some time then try again.';
    }
    while(0);
  }

?>

<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<title>Create a Post | Social 02</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/library/css/main.css">
<link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/library/css/bootstrap.min.css">
<style>
</style>
<body>
<?php
  echo BuildNavigation();
?>
<div class="container">
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10 debug">
        <div class="border-2 rounded-3 px-3 pt-5">
          <form name="xFORM" method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>" enctype="multipart/form-data" class="px-5 pt-5">
          <div class="mb-3 mt-3">
              <label for="xTEXT" class="form-label">Post Text</label>
              <textarea id="xTEXT" name="xTEXT" class="form-control"></textarea>
            </div>
            <div class="mb-3 mt-3">
              <label for="xIMAGE" class="form-label">Post Image</label>
              <input type="file" accept="image/*" id="xIMAGE" name="xIMAGE" class="form-control">
            </div>
            <div class="col-auto">
              <input type=submit name="xSUBMIT" class="btn btn-primary mb-3" value="SUBMIT">
            </div>
          </form>
        </div>
      </div>
      <div class="col-1"></div>
    </div>
  </div>
</body>
</html>