<?php

  // Ensure session variables are available
  session_start();

  // Set server timezone to America/New_York (EST)
  date_default_timezone_set('America/New_York');

  // Include the environment library
  require $_SERVER['DOCUMENT_ROOT'] . '/spring_2022/csis408/social02/env/tables.phtml';
  require $_SERVER['DOCUMENT_ROOT'] . '/spring_2022/csis408/social02/env/env.phtml';
  require $_SERVER['DOCUMENT_ROOT'] . '/spring_2022/csis408/social02/env/db.phtml';
  require $_SERVER['DOCUMENT_ROOT'] . '/spring_2022/csis408/social02/env/functions.phtml';

  // Get last modification of the requested file -- Debug to ensure successful FTP deploy.
  if(0 && (strpos($_SERVER['PHP_SELF'], 'feeder.phtml') === false))
  {
    echo "Last modified: " . date("F d Y H:i:s.", getlastmod()) . '<br>' . "\n";
    echo "Current User: " . $myACCOUNT['full_name'] . ' - UID: ' . $myACCOUNT['id'] . '<br>' . "\n";
  }

?>